### ISSUE TITLE
zeros and wrong weights in large weights matrix

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#161]
### What you were trying to do
Calculate a weights matrix with ``pyndl.ndl.ndl`` that has more cells than 2^32 cells.

### What actually happened
Cells in the weights matrix that are above 2^32 stay zero and values below this might get wrong values compared to calculating these outcomes in a smaller sized matrix.

### System details
64 bit Linux.

**Comment by derNarr** [comment]
The whole behaviour hints strongly at an integer overflow of the index variables in the cython code. This is a severe bug that needs fixing as soon as possible. Thanks to Yu-Ying for finding the bug.

### TODO

- [ ] build a test case that checks the cython code for the int size and if an overflow happens
- [ ] build a test case which actually learns a large weights matrix, if the system has enough memory for running this test
- [ ] fix the bug

**Comment by derNarr** [comment]
The whole behaviour hints strongly at an integer overflow of the index variables in the cython code. This is a severe bug that needs fixing as soon as possible. Thanks to Yu-Ying for finding the bug.

### TODO

- [ ] build a test case that checks the cython code for the int size and if an overflow happens
- [ ] build a test case which actually learns a large weights matrix, if the system has enough memory for running this test
- [ ] fix the bug

**Comment by derNarr** [comment]
We use `unsigned int` in the cython file and in the intermediate file.
